services:
  - type: web
    name: donsang-guinee
    env: node
    # Repo root est déjà le projet Next.js; ne pas cibler un sous-dossier inexistant
    # rootDir: .
    plan: starter
    region: oregon
    buildCommand: npm install --no-audit --no-fund && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npx prisma db push && npx next start -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
